workspace(name = "tink_cc_gcpkms_examples")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Direct dependencies.
http_archive(
    name = "com_google_absl",
    sha256 = "de649bb5a392b1c63a67f66bf992a72ff3c4b6b130b8b9dc95c31b962ec49e7a",
    strip_prefix = "abseil-cpp-20240722.1",
    urls = [
        "https://github.com/abseil/abseil-cpp/archive/refs/tags/20240722.1.zip",
    ],
)

http_archive(
    name = "tink_cc",
    sha256 = "3080600b6c38421ebaca5bfc460aa965afc88c877695c080019a8905f0f1c1b8",
    strip_prefix = "tink-cc-2.1.1",
    urls = ["https://github.com/tink-crypto/tink-cc/releases/download/v2.1.1/tink-cc-2.1.1.zip"],
)

local_repository(
    name = "tink_cc_gcpkms",
    path = "../",
)

load("@tink_cc_gcpkms//:tink_cc_gcpkms_deps.bzl", "tink_cc_gcpkms_deps")

tink_cc_gcpkms_deps()

load("@tink_cc_gcpkms//:tink_cc_gcpkms_deps_init.bzl", "tink_cc_gcpkms_deps_init")

tink_cc_gcpkms_deps_init(register_go = True)
