workspace(name = "tink_cc_gcpkms_examples")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Direct dependencies.
http_archive(
    name = "com_google_absl",
    sha256 = "1692f77d1739bacf3f94337188b78583cf09bab7e420d2dc6c5605a4f86785a1",
    strip_prefix = "abseil-cpp-20250814.1",
    urls = [
        "https://github.com/abseil/abseil-cpp/releases/download/20250814.1/abseil-cpp-20250814.1.tar.gz",
    ],
)

http_archive(
    name = "tink_cc",
    sha256 = "06c4d49b0b1357f0b8c3abc77a7d920130dc868e4597d432a9ce1cda4f65e382",
    strip_prefix = "tink-cc-2.4.0",
    urls = ["https://github.com/tink-crypto/tink-cc/releases/download/v2.4.0/tink-cc-2.4.0.zip"],
)

local_repository(
    name = "tink_cc_gcpkms",
    path = "../",
)

load("@tink_cc_gcpkms//:tink_cc_gcpkms_deps.bzl", "tink_cc_gcpkms_deps")

tink_cc_gcpkms_deps()

load("@tink_cc_gcpkms//:tink_cc_gcpkms_deps_init.bzl", "tink_cc_gcpkms_deps_init")

tink_cc_gcpkms_deps_init(register_go = True)
